### ISSUE TITLE
Use Emscripten to replace OpenPGP.js?

### ISSUE THREAD

**Issue by dcposch** [dcposch/scramble#25]
Decryption with OpenPGP.js is slow. Running single threaded (ie, no Web Workers) on a Core i7, it takes ~60 milliseconds to decrypt a single subject. For a large inbox this leads to unacceptable lag.

OpenPGP.js has other aspects that make me question its quality. For example, attempting decryption with an invalid key results in a cryptic unrelated error message. Few comments. Blocks of commented out code and commented out debugging print calls.

If possible, it would be nice to use a more widely-used OpenPGP implementation such as GPG (libgcrypt) via Emscripten. This may be safer and also faster.

**Comment by mnaamani** [comment]
I worked on compiling libgcrypt and libotr in emscripten overriding some compiled code with bigint.js to speed things up, maybe someone will find it useful:

https://github.com/mnaamani/crypto-emscripten
